using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ButterflyMover : MonoBehaviour
{
    public float speed;
    public bool vertical;
    public float changeTime = 3.0f;

    
    Rigidbody2D rigidbody2D;
    float timer;
    int direction = 1;
    bool broken = true;
    
    Animator animator;
   

    void Start()
    {
        rigidbody2D = GetComponent<Rigidbody2D>();
        timer = changeTime;
        animator = GetComponent<Animator>();

    }

    void Update()
    {
        //remember ! inverse the test, so if broken is true !broken will be false and return wonâ€™t be executed.
        if(!broken)
        {
            return;
        }
        
        timer -= Time.deltaTime;

        if (timer < 0)
        {
            direction = -direction;
            timer = changeTime;
        }
    }
    
    void FixedUpdate()
    {

      Vector2 position = rigidbody2D.position;

        if (vertical)
        {
            position.y = position.y + Time.deltaTime * speed * direction;
           // animator.SetFloat("Move X", 0);
          //  animator.SetFloat("Move Y", direction);
        }
        else
        {
            position.x = position.x + Time.deltaTime * speed * direction;
          //  animator.SetFloat("Move X", direction);
           // animator.SetFloat("Move Y", 0);
        }
        
        rigidbody2D.MovePosition(position);
    }
    
}
